# Base de datos
spring.datasource.url=jdbc:h2:mem:huertodev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

frontend.url=https://eariasvalor.github.io/HuertoCarlos-front

notification.media.max-size-bytes=5242880
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Springdoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# Logs
logging.level.org.springframework.security=DEBUG
logging.level.com.huerto=DEBUG

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# WhatsApp
whatsapp.api.token=${WHATSAPP_API_TOKEN}
whatsapp.api.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.api.version=v18.0
whatsapp.templates.status-change=order_status_change
whatsapp.templates.new-order-admin=new_order_admin
whatsapp.templates.manual-text=manual_notification
whatsapp.templates.manual-image=manual_notification_image
whatsapp.admin.phone=${ADMIN_PHONE}
whatsapp.retry.enabled=true
whatsapp.retry.delay-ms=300000

#Twilio
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.whatsapp-from=${TWILIO_WHATSAPP_FROM}
twilio.admin.phone=${ADMIN_PHONE}
